    - name: add digital-ocean droplet 
      digital_ocean:
            state: present
            command: droplet
            name: centos-7{{ droplet_item.name }}
            api_token: "{{ doapitoken }}"
            region_id: fra1
            ssh_key_ids: "{{ my_key.ssh_key.id }}"
            size_id: "{{ droplet_item.sizeid }}"
            image_id: centos-7-x64
            wait_timeout: 500
      register: d_parms

    - name: print digital-ocean droplet info 
      debug:
        msg: "ID is {{d_parms.droplet.id }} IP is {{ d_parms.droplet.ip_address }}"

    - name: Add new droplet into ansible-playbook_in-memory inventory [host,group]
      add_host: 
         name: "{{ d_parms.droplet.ip_address }}"
         groups: "launched"
         ansible_user: "root"
         ansible_ssh_common_args: "-oStrictHostKeyChecking=no"
         ansible_host_key_checking: False
#         ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"
#         ansible_python_interpreter: /usr/bin/python3.6

    - name: Wait for SSH to come up
      local_action: wait_for host={{ d_parms.droplet.ip_address }} port=22 delay=15 timeout=320 state=started           

#    - name: SSH ssh-keyscan
#      command: "ssh-keyscan -H {{d_parms.droplet.ip_address}} >> ~/.ssh/known_hosts"           

    - name: check SSH
      command: "ssh root@{{d_parms.droplet.ip_address}} uname -a"           


#from here https://gist.github.com/rdhyee/7047660
